### ISSUE TITLE
reply by email not working

### ISSUE THREAD

**Issue by heyTimApple** [pimoore/microdotblog-tufte#1]
Hey, the reply by email feature doesn't seem to be enabled after I put email in config.json.. 

"params": {
		"description": "Thoughts, Stories, and Musings",
		"itunes_description": "[ITUNES_DESCRIPTION]",
		"itunes_category": "[ITUNES_CATEGORY]",
		"itunes_subcategory": "[ITUNES_SUBCATEGORY]",
		"itunes_author": "[ITUNES_AUTHOR]",
		"itunes_email": "[ITUNES_EMAIL]",
		"itunes_cover": "[ITUNES_COVER]",
		"twitter_username": "[TWITTER_USERNAME]",
		"github_username": "[GITHUB_USERNAME]",
		"instagram_username": "[INSTAGRAM_USERNAME]",
		"site_id": "[SITE_ID]",
		"paginate_home": false,
		"paginate_categories": false,
		"paginate_replies": false,
		"theme_seconds": "0",
		"plugins_css": [],
		"plugins_js": [],
		"plugins_html": [],
		"subtitle": "Thoughts, Stories, and musings...",
		"mailto": "tim@timapple.com"

**Comment by pimoore** [comment]
Looking at your site now I see the post metadata is different, and the article width is also off.  That’s definitely strange if this was freshly installed from the plugin.  When you removed all the files, you also removed any custom CSS you were using prior, correct?  Can you post a screenshot of your Design section showing the template and custom theme section? I still feel like something is still hanging around causing a conflict, as your config.json changes were correct.

**Comment by heyTimApple** [comment]
I will check it out tomorrow. I wonder if it could be another plugin?

**Comment by pimoore** [comment]
It very well could be, you also have to make sure you set the template to blank before installing the plugin.

**Comment by rretsiem** [comment]
I installed the Tufte theme today as well and have the same issue as @heyTimApple. The config.json is configured as described in readme but it not shows up below the post.
If it's a plugin the prevents it from displaying it, I haven't figured out which one yet. Will do some tests but as I looked on the Readme.md on the Github repo, even there is no email link or anything displayed on the screenshots for the post examples to get a glue how this should look in real life.

**Comment by rretsiem** [comment]
Update from my site, of course shortly after I posted the above issue...
It works now for me, when I uninstall all plugins, set the Design-template to "blank", save all the settings and then install the Tufte plugin and afterwards all the other plugins. So fixed for me that way, hope this helps others as well.

**Comment by pimoore** [comment]
Thanks @rretsiem, I’ve updated the README to include these steps in the event others encounter the same issue.

**Comment by pimoore** [comment]
> Update from my site, of course shortly after I posted the above issue...
> It works now for me, when I uninstall all plugins, set the Design-template to "blank", save all the settings and then install the Tufte plugin and afterwards all the other plugins. So fixed for me that way, hope this helps others as well.

@heyTimApple - Are you able to give the above steps a try and see if it works on your blog as well?

**Comment by heyTimApple** [comment]
Will do in the morning, I have to save some modifications to plug-ins so I can redo it again after resetting. Today was busy with Halloween and kiddos.

Tim

**Comment by heyTimApple** [comment]
Ok, it's official, did all the steps listed above and I'm functioning now. I also put plugins back one by one to make sure none of them were the culprit, but seems to be fine still.

**Comment by pimoore** [comment]
Awesome, thanks for your patience Tim, happy you got it working!
