### ISSUE TITLE
Description of Meta is displayed wrong when preview on e.g. Discord

### ISSUE THREAD

**Issue by rretsiem** [pimoore/microdotblog-tufte#3]
After playing around with Tufte them which I really like I found one small issue and don't know how to fix it, so I may need some help.
When I post a link to a Discord chat, previously the Summary was displayed with the link on e.g. the Marfa theme which I used before. Now with the Tufte theme, the text is always "musings from the nib".
Which is set as _description_ in config.json, and may is right when linking to my home page of the blog, but when linking to a specific blog post I think the e.g. Hugo-default Summary should be displayed as before.
Is there a chance to get that working?

With Marfa theme preview in Discord: 
![image](https://user-images.githubusercontent.com/248836/139603263-d0fd8189-16c4-45aa-93bb-794417f93f32.png)

With Tufte theme: 
![image](https://user-images.githubusercontent.com/248836/139603276-a5f59e28-c50c-42a4-9ff3-bce14c8fb959.png)

**Comment by pimoore** [comment]
That’s strange, as when I compare the metadata from the source code of these two posts, I can’t see why it’s not pulling the same summary info from the previous theme.  I’ll keep looking into this and get back to you.

**Comment by pimoore** [comment]
@rretsiem - Hi René, sorry it took me some time to get back to you on this.  I think this issue was coming from the code in the Open Graph template (og.html).  Micro.blog actually has a plugin for this, but I copied and replaced the original code in the og.html with the code the plugin adds anyway, and when I tested in Signal it was showing post summary information.  Here’s the code:

`

{{ if .Title }}
	<meta property="og:title" content="{{ .Title }}" />
{{ else }}
    <meta property="og:title" content="{{ .Site.Title }}" />
{{ end }}

<meta property="og:description" content="{{ with .Description }}{{ . }}{{ else }}{{if .IsPage}}{{ .Summary }}{{ else }}{{ with .Site.Params.description }}{{ . }}{{ end }}{{ end }}{{ end }}" />
<meta property="og:type" content="{{ with .Title }}article{{ else }}website{{ end }}" />
<meta property="og:url" content="{{ .Permalink }}" />

{{ with .Params.images }}
    {{ range first 6 . }}
        <meta property="og:image" content="{{ . | absURL }}" />
    {{ end }}
{{ end }}

{{ with .Params.audio }}
    <meta property="og:audio" content="{{ . }}" />
{{ end }}

{{ with .Params.videos }}
    {{ range first 1 . }}
        <meta property="og:video" content="{{ . | absURL }}" />
    {{ end }}
{{ end }}

{{ if .IsPage }}
  {{ if not .PublishDate.IsZero }}
    <meta property="article:published_time" content="{{ .PublishDate.Format "2006-01-02T15:04:05-07:00" | safeHTML }}"/>
  {{ else if not .Date.IsZero }}
    <meta property="article:published_time" content="{{ .Date.Format "2006-01-02T15:04:05-07:00" | safeHTML }}"/>
  {{ end }}

  {{ if not .Lastmod.IsZero }}
    <meta property="article:modified_time" content="{{ .Lastmod.Format "2006-01-02T15:04:05-07:00" | safeHTML }}"/>
  {{ end }}
{{ else }}
  {{ if not .Date.IsZero }}
    <meta property="og:updated_time" content="{{ .Date.Format "2006-01-02T15:04:05-07:00" | safeHTML }}"/>
  {{ end }}
{{ end }}

{{ with .Site.Params.title }}
<meta property="og:site_name" content="{{ . }}" />
{{ end }}

{{ if .IsPage }}
  {{ range .Site.Authors }}
    {{ with .Social.facebook }}
      <meta property="article:author" content="https://www.facebook.com/{{ . }}" />
    {{ end }}

    {{ with .Site.Social.facebook }}
      <meta property="article:publisher" content="https://www.facebook.com/{{ . }}" />
    {{ end }}
  {{ end }}

    <meta property="article:section" content="{{ .Section }}" />

  {{ with .Params.tags }}
    {{ range first 6 . }}
      <meta property="article:tag" content="{{ . }}" />
    {{ end }}
  {{ end }}
{{ end }} `

Please give this a try and let me know if it solves the issue for you!

**Comment by pimoore** [comment]
@rretsiem - Hi Rene, sorry it took me some time to get back to you.  I believe the source of the issue you were seeing was the Open Graph template (og.html), which controls the sharing card functionality to various services.  Micro.blog actually has a plugin for this, but to prevent having to install it I just copied and replaced the og.html code with that of the plugin.  Testing a couple of posts of mine with Signal had the card displaying the post summary as expected.

Please give this a try and let me know if it works for you.  Here’s the code:

```
<!-- Posts with titles -->

{{ if .Title }}
	<meta property="og:title" content="{{ .Title }}" />
{{ else }}
    <meta property="og:title" content="{{ .Site.Title }}" />
{{ end }}

<meta property="og:description" content="{{ with .Description }}{{ . }}{{ else }}{{if .IsPage}}{{ .Summary }}{{ else }}{{ with .Site.Params.description }}{{ . }}{{ end }}{{ end }}{{ end }}" />
<meta property="og:type" content="{{ with .Title }}article{{ else }}website{{ end }}" />
<meta property="og:url" content="{{ .Permalink }}" />

{{ with .Params.images }}
    {{ range first 6 . }}
        <meta property="og:image" content="{{ . | absURL }}" />
    {{ end }}
{{ end }}

{{ with .Params.audio }}
    <meta property="og:audio" content="{{ . }}" />
{{ end }}

{{ with .Params.videos }}
    {{ range first 1 . }}
        <meta property="og:video" content="{{ . | absURL }}" />
    {{ end }}
{{ end }}

{{ if .IsPage }}
  {{ if not .PublishDate.IsZero }}
    <meta property="article:published_time" content="{{ .PublishDate.Format "2006-01-02T15:04:05-07:00" | safeHTML }}"/>
  {{ else if not .Date.IsZero }}
    <meta property="article:published_time" content="{{ .Date.Format "2006-01-02T15:04:05-07:00" | safeHTML }}"/>
  {{ end }}

  {{ if not .Lastmod.IsZero }}
    <meta property="article:modified_time" content="{{ .Lastmod.Format "2006-01-02T15:04:05-07:00" | safeHTML }}"/>
  {{ end }}
{{ else }}
  {{ if not .Date.IsZero }}
    <meta property="og:updated_time" content="{{ .Date.Format "2006-01-02T15:04:05-07:00" | safeHTML }}"/>
  {{ end }}
{{ end }}

{{ with .Site.Params.title }}
<meta property="og:site_name" content="{{ . }}" />
{{ end }}

{{ if .IsPage }}
  {{ range .Site.Authors }}
    {{ with .Social.facebook }}
      <meta property="article:author" content="https://www.facebook.com/{{ . }}" />
    {{ end }}

    {{ with .Site.Social.facebook }}
      <meta property="article:publisher" content="https://www.facebook.com/{{ . }}" />
    {{ end }}
  {{ end }}

    <meta property="article:section" content="{{ .Section }}" />

  {{ with .Params.tags }}
    {{ range first 6 . }}
      <meta property="article:tag" content="{{ . }}" />
    {{ end }}
  {{ end }}
{{ end }}
```

**Comment by rretsiem** [comment]
Thanks, will test this shortly. Do I have to copy&paste that code into the Tufte custom themes og.html and have to deactivate the OG Plugin on M.B. as well?

**Comment by rretsiem** [comment]
O.K. faster than expected. I replaced all the code with the above one in the og.html and uninstalled the OpenGraph Plugin. A quick test by sharing a post to Discord looks good!

Thanks for your help!
