### ISSUE TITLE
Customization of Tufte Template files like config.json

### ISSUE THREAD

**Issue by mikesplaces** [pimoore/microdotblog-tufte#4]
I found when doing the recent update via the plugin tool on micro.blog that customizations I had made to the config.json file needed to be done again with the update. Not so much a bug but perhaps you should check to see if this happens on your test blog and let people know if it does to check any changes they made like for the description and tagline or email address. Pretty easy actually to just go back and change back. I had also made changes to the default.css file to make the tagline lowercase. This was overwritten too with the new install. Maybe you can check your test server for these things and see if what I found was an anomaly or mention in release notes you publish about checking any customizations made.

**Comment by pimoore** [comment]
Thanks for bringing this up!  Yes, any time the plug-in updates it will revert these changes, so I’ll add a note to the README file to be aware and save any changes.

**Comment by manton** [comment]
#7 also makes this easier to deal with because Micro.blog essentially maintains the config without needing a custom theme.

**Comment by pimoore** [comment]
@mikesplaces I’ve updated the plug-in with Manton’s pull request to add user configuration settings for the subtitle parameter, and also added mailto myself.  If you update to the latest version (1.1.2) it should solve this issue going forward.
