### ISSUE TITLE
Show Replies below article?

### ISSUE THREAD

**Issue by rretsiem** [pimoore/microdotblog-tufte#8]
using your theme for a while and now tried to add the replies to my blog posts, including Brid.gy WebMentions below the blog posts. I've enabled all the settings in M.B. _include conversations on posts page_ but they do not appear there.

Is there an extra setting I've to enable to enable that features?
P.S. I've checked the blog post source code and the script=conversations.js is loaded.

**Comment by pimoore** [comment]
If I’m understanding correctly the MB replies are showing but Bridgy ones aren’t?  I’m afraid I’m not familiar with Bridgy, so that would be a better question for @manton.

**Comment by rretsiem** [comment]
Oh no, sorry for not being clearer here. None of the replies are showing up at all. "Just" the Reply via Mail button which I use as a plugin since the latest version 1.3 didn't include that anymore.

**Comment by pimoore** [comment]
I’m not sure what the issue would be unless something errored out while trying to build the site.  Are you using the latest version of the theme plug-in?  If you are, perhaps try reinstalling it and see if the issue persists.  Also check the Design page for any error messages.

**Comment by manton** [comment]
On first glance, everything appears to be set up correctly… @rretsiem is there a specific post URL where you're expecting replies/Webmentions and not seeing them?

**Comment by rretsiem** [comment]
> @rretsiem is there a specific post URL where you're expecting replies/Webmentions and not seeing them?

Yes @manton, or I don't understand something. This post: https://microblog.renem.net/2022/01/16/free-sundayswing-ideas.html was crossposted to Twitter via M.B.

Has replies, likes and retweets on Twitter: https://twitter.com/Stratinator/status/1482727208422629379

**Comment by rretsiem** [comment]
@manton Had a look in the brid.gy logs after I manually started a crawl:

```
D 2022-01-27 21:27:10.954102+00:00 processing permalink: https://microblog.renem.net/2022/01/16/free-sundayswing-ideas.html
I 2022-01-27 21:27:10.954382+00:00 requests.head https://microblog.renem.net/2022/01/16/free-sundayswing-ideas.html {'headers': {'User-Agent': '...', 'Accept': '...'}}
I 2022-01-27 21:27:11.059143+00:00 Received 200
D 2022-01-27 21:27:11.060479+00:00 fetching post permalink https://microblog.renem.net/2022/01/16/free-sundayswing-ideas.html
I 2022-01-27 21:27:11.060799+00:00 requests.get https://microblog.renem.net/2022/01/16/free-sundayswing-ideas.html {'gateway': False, 'headers': {'User-Agent': '...', 'Accept': '...'}}
I 2022-01-27 21:27:11.126365+00:00 Received 200
D 2022-01-27 21:27:11.173098+00:00 no syndication links from https://microblog.renem.net/2022/01/16/free-sundayswing-ideas.html to current source Stratinator (Twitter).
```

nothing more for this URL in the log found.
Sorry for hijacking your Repo @pimoore ;-)

**Comment by pimoore** [comment]
No worries @rretsiem, I’ll leave this thread open until there’s a resolution.

**Comment by rretsiem** [comment]
@manton something happened a few hours ago, I got push notifications in the iOS app with the replies for the mentioned blog post. But only for that post. Testing something?

**Comment by manton** [comment]
Interesting! I haven't changed anything with that. Maybe Bridgy picked up some older posts and just processed them? I guess let us know if going forward this is an issue again.

**Comment by pimoore** [comment]
I’ll go ahead and close this issue for now then.
